### PR TITLE
created navigation tabs

### PR DESCRIPTION
**Pull request by joyang15**
Created navigation tabs, also made some styling changes. However, I believe going forward we can choose a theme from here (https://rstudio.github.io/py-shinyswatch/reference/theme.minty.html) and change the CSS as we see fit. The .gitignore file was changed to ignore a __pycache__ file that randomly appeared for me.

### CODE REVIEW

**Comment by meenuandoor** [comment]
1. https://bootswatch.com/zephyr/
2. https://bootswatch.com/minty/
3. https://bootswatch.com/materia/

**Other options**
https://bootswatch.com/journal/
https://bootswatch.com/lumen/
https://bootswatch.com/lux/
https://bootswatch.com/morph/
https://bootswatch.com/pulse/
https://bootswatch.com/yeti/

**Comment by joyang15** [comment]
to see the UI with the theme, run: pip install -r requirements.txt

**Comment by joyang15** [comment]
> to see the UI with the theme, run: pip install -r requirements.txt

**Comment by meenuandoor** [comment]
Approved, I fixed a minor typo.

**Review by meenuandoor — APPROVED** [review]
Great work!

**Pull request merged**
