### PR TITLE
Storage script

### PR DESCRIPTION
**Pull request by twarep**
## Checklist
- [x] Did I add this pull request into the appropriate Notion ticket? If not, create a ticket for this PR.

## What I Did
Created a file called storage.py. It contains a bunch of methods that relate to pushing data into our database. For when the database connection string changes, the only thing that will have to change is the DATABASE_URL in the .env file, saving us a lot of work.

Modified transformation.py and scraper.py where appropriate.

## How I Did it?
Used SQLAlchemy, since pandas doesn't let you push data frames into a database unless the connection engine is via SQLAlchemy.

## How to Test?
You will need to setup the repository in linux. The instructions to do that is the same as in the readme, except you have to create the virtual environment like this: `python3.9 -m venv venv` to ensure that the python version is 3.9 (the minimum needed to run our app)
1. Delete the entire database using DROP SCHEMA public CASCADE;
2. Recreate the database using CREATE SCHEMA public;
3. Run scraper.py (I removed the pipeline directory, so just run it within the electrifly directory)
4. Check the database in DBeaver. It should be fully populated, looking like this:
Screen Shot 2023-07-20 at 7 39 43 PM
If you need help connecting to our database using DBeaver, see the Notion ticket.

### CODE REVIEW

**Comment by vik01** [comment]
This doesn't work with Windows machines. Vikram to look into Firefox driver

**Comment by twarep** [comment]
Storage script works on linux now, specifically for the postgres database in the server. When testing, ensure you are on the school network or are connected to VPN when testing the code. I updated the notion ticket to have the DBeaver connection string for our prod database.

**Review by vik01 — CHANGES_REQUESTED** [review]
Hey Peter. 

**NOTE:** I ran this on the server through remote desktop.

I have reviewed your program. Its good. But there is a major problem. I get this error when cleaning the DB and running the `python3.9 scraper.py` script. This is the error:

image

I think this problem is happening because we are taking both `Flights Test` and `Flight test and charging` on line 187: `if current_flight_type not in ["Flight test and charging", "Flight test"]:`.

The reason I say this is because that there is a `Flight test and charging` data for July 22d on the Pipistrel UI (image below). I downloaded that and checked the CSV file, and basically found that the data is only for Charging. Which makes the error of not being able to find the `ias_derivative` column in the data, valid. I think we should **only** look for `Flight Test` data in the `scraper.py`. This should solve the error.

image

**Comment by vik01** [comment]
Hey Peter, I fixed that error. But now I am getting another error:

image

For the first comment, I was using the old neon database to do the testing. But I switched over to the new one (that you put in the task, with updating the `.env` file). However, with that, I am getting the above error. I could try fixing it, but since its your task, I don't want to dabble too much into it and mess something up. I already made the change I mentioned in my comment above.

**Comment by twarep** [comment]
Hey Vikram,

Thanks for the fix with flight test with charging. Initially those data for other flights contained flight data, which means we might be losing a flight or two of data by removing the options as you made in (https://github.com/twarep/electrifly/pull/12/commits/189e2862f12df4a2c6bc9909aee5fbc15e087f83)

Looks like my testing instructions were to blame for this problem. Problem is that on neon when creating a schema it automatically was assigned to user, but when running CREATE SCHEMA public; the schema is created under the "postgres" user, not our "user" user. Since user didn't have access to the schema, it could not see the schema and was creating that error.

Please try testing again, but when recreating the schema, use this command instead:

CREATE SCHEMA public AUTHORIZATION "user";

This ensures the public schema is owned by "user", and it should work like this. Your code in (https://github.com/twarep/electrifly/pull/12/commits/179c896bf00bd9ad555e1049df84704ad04d33c3) is redundant, however, and can be removed.

**Review by twarep — COMMENTED** [review]
Code is all good, you can remove the code in the second commit if you want.

**Review by vik01 — APPROVED** [review]

**Comment by vik01** [comment]
Got rid of the changes I made in my second last commit. Then tested the scraper.py. It works as intended. Merging now.

**Pull request merged**
