### PR TITLE
Transformation tests

### PR DESCRIPTION
**Pull request by twarep**
## Checklist
- [x] Did I add this pull request into the appropriate Notion ticket? If not, create a ticket for this PR.

## What I Did
What files git you edit and why/for what purpose?
Created test_transformation.py to store all the tests for the transformation.py file.

## How to Test?
Manual testing? Automated testing? E2E testing? Smoke tests?

Run pytest locally, should see that 6 tests in test_transformation.py pass:
Screen Shot 2023-10-17 at 7 47 10 PM

### Relevant Links
Any tutorials or other resources used to help with this task. You can also cite the documentation.

### CODE REVIEW

**Comment by joyang15** [comment]
I get the following assertion error: 
image
image
Not sure if this is just a problem on my end?

**Comment by twarep** [comment]
Can you run 
`print(expected_df.to_string())` and
`print(actual_df.to_string())`
just above the assertion and send me the screenshot of the two dfs?

I can't diagnose the error with this information.

**Comment by joyang15** [comment]
image

**Comment by joyang15** [comment]
It looks like the wind direction data types are causing another assertion error:
image

**Review by joyang15 — APPROVED** [review]
Awesome job! The branch is ready to be merged

**Pull request merged**
