### PR TITLE
App running bug fix

### PR DESCRIPTION
**Pull request by vik01**
## What I Did
- Edited the `db.sql` and `queries.py` scripts to get rid of the `NOT NULL` constraint on the `wind_direction` column.
- Tested the `scrapper.py` on the Linux server, found that the chromedriver download is not required for Linux. Made that test.

## How I Did it?
- Just changed the code as shown the `files changed` section of this PR.

## How to Test?
- Manually tested the `app.py` to see if everything runs. Tested on Windows.

### CODE REVIEW

**Review by NayeemaNonta — CHANGES_REQUESTED** [review]
does not work for me, I suspect something wrong with the db_url variable

Screenshot 2023-10-03 at 9 19 42 PM

It works when I hard code the db_url variable to: `db_url = "postgresql+psycopg2://user:velis@129.97.25.100:5432/velis"`

**Comment by twarep** [comment]
Most likely, NoneType means that os.getenv is not getting anything, make sure your .env file is okay.

**Comment by NayeemaNonta** [comment]
Screenshot 2023-10-08 at 12 28 48 AM

Still getting this error, my env file is correct, I had no issues with it when I was running the scarper before.

**Review by NayeemaNonta — APPROVED** [review]
Works great, thanks @twarep  for fixing the bug I got

**Pull request merged**
