### PR TITLE
simulation table in UI

### PR DESCRIPTION
**Pull request by meenuandoor**
## Checklist
- [x] Did I add this pull request into the appropriate Notion ticket? If not, create a ticket for this PR.
**Note:** Put an x into the box like this [x] to check these off

## What I Did
Edited app.py and simulation to make the UI appear

## How I Did it?
Edited app.py and simulation to make the UI appear

## How to Test?
Run app.py and open the simulation tab, verify that the forecasted table appears for the zones. 
image

### Relevant Links
Any tutorials or other resources used to help with this task. You can also cite the documentation.

### CODE REVIEW

**Review by twarep — CHANGES_REQUESTED** [review]
The output on the app looks good, but there are too many print statements. Please remove all the prints from console as they are not needed.

Also, you have created a bunch of csv files that we don't need, please delete the code that generates them.

**Comment by meenuandoor** [comment]
Okay we did that

**Comment by meenuandoor** [comment]
@twarep - we also added in the upcoming flights table

**Review by twarep — APPROVED** [review]
LGTM!

**Pull request merged**
