### PR TITLE
Upload screen recent records table

### PR DESCRIPTION
**Pull request by NayeemaNonta**
## Checklist
- [x] Did I add this pull request into the appropriate Notion ticket? If not, create a ticket for this PR.
**Note:** Put an x into the box like this [x] to check these off

## What I Did
- Created the flight_weather_data_view in the database 

Screen Shot 2023-07-25 at 2 16 36 AM

- Upload screen most recent records table 

Screen Shot 2023-07-25 at 2 18 02 AM

## How I Did it?
All required imports should be included in app.py, but I used psycopg2 and sqlalchemy to do this in the UI, and SQL query script for the view in the database. 

## How to Test?
Manual test, make sure the table populates, make sure all the columns are there. 
Check [This Notion Page](https://www.notion.so/UI-Upload-Screen-Most-Recent-Records-Table-7b781bd1542f48bd86c0987789460c4b) to ensure all the appropriate columns are shown in the collapsed mode. 

### Relevant Links
Any tutorials or other resources used to help with this task. You can also cite the documentation.
- https://appsilon.com/shiny-for-python-databases-mysql-postgres/#:~:text=Shiny%20for%20Python%20%E2%80%93%20How%20to%20Connect%20to%20Databases,-The%20dashboard%20you&text=You%20don't%20have%20to,to%20the%20database%20%E2%80%93%20connect_to_db()%20
- https://shiny.posit.co/py/api/reactive.Effect.html

### CODE REVIEW

**Comment by NayeemaNonta** [comment]
@vik01 where should I add the script I used to create the database view in the code? Would I need to call it in scraper.py since the view needs to update every time the scraper is run? Just wanna confirm with you first

**Comment by NayeemaNonta** [comment]
Note: view SQL script will be added to the upload/refresh button once it's done

**Comment by joyang15** [comment]
image
I'm not able to see pitch, roll, and requested torque - did we decide to remove them from the collapsed table?

**Comment by NayeemaNonta** [comment]
> image I'm not able to see pitch, roll, and requested torque - did we decide to remove them from the collapsed table?

Yes, those columns were removed after our meeting with Mehrdad on Tuesday. Forgot to update the screenshot in the PR template. Will also be adding the DATE col in the next iteration for this screen.

**Review by joyang15 — APPROVED** [review]
The table looks great, I'm able to see the collapsed and full version, great job! The branch is ready to be merged.

**Pull request merged**
